version: 2

sources:
  - name: launchpad
    description: "Crowjacket Database"
    database: LAUNCHPAD_DB
    schema: PUBLIC
    tables:
      - name: customers
      - name: loyalty_points
      - name: orders
      - name: order_items
      - name: products

